### ISSUE TITLE
Conversion fails when script tag doesn't contain src parameter.

### ISSUE THREAD

**Issue by kaivalyapendse** [Hall-Erik/ng2django#2]
Conversion fails in ng2django command when the any of the script tag in HTML doesn't contain scr parameter. 
Following is the error:

```
Traceback (most recent call last):
  File "C:\Python379\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python379\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Git\rubiscape3.7.9\Scripts\ng2django.exe\__main__.py", line 7, in <module>
  File "e:\git\rubiscape3.7.9\lib\site-packages\ng2django\ng2django.py", line 122, in main
    if el.get("src")[0:4] != "http":
TypeError: 'NoneType' object is not subscriptable
```
I resolved the same by using exception handling on line #122 in ng2djnago.py.

PS : I would like to contribute a fix in the same way/ handling get method in a better way. Kindly let me know.

**Comment by Hall-Erik** [comment]
Nice! Go ahead and open a PR.

**Comment by kaivalyapendse** [comment]
Done! :) PR Raised -> #3

**Comment by Hall-Erik** [comment]
Merged and pushed into PyPi. Thank you!
